""" Code is generated by ucloud-model, DO NOT EDIT IT. """

import typing

from ucloud.core.client import Client
from ucloud.services.umon.schemas import apis


class UMonClient(Client):
    def __init__(
        self, config: dict, transport=None, middleware=None, logger=None
    ):
        super(UMonClient, self).__init__(config, transport, middleware, logger)

    def get_metric(self, req: typing.Optional[dict] = None, **kwargs) -> dict:
        # build request
        d = {"ProjectId": self.config.project_id, "Region": self.config.region}
        req and d.update(req)
        d = apis.GetMetricRequestSchema().dumps(d)

        # build options
        kwargs["max_retries"] = 0  # ignore retry when api is not idempotent

        resp = self.invoke("GetMetric", d, **kwargs)
        return apis.GetMetricResponseSchema().loads(resp)
